version: '3'
services:
  app:
    image: eduardomota/nodejs
    container_name: nodejs
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/app
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'